apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: cont1
        image: pradeep211031/employee-attendance-tracker:latest
        ports:
        - containerPort: 9091
